name: Scheduled Health Check

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  health_check_job:
    runs-on: ubuntu-latest
    name: Check all sites
    steps:
      - uses: actions/checkout@v2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
      - name: Testing PHP version
        run: php -v
      - name: Run PHP Script
        run: php ./health-check.php
        env:
          PROD: ${{ secrets.ProdURL }}
          DEV: ${{ secrets.DevURL }}
          TRAINING: ${{ secrets.TrainingURL }}
          TEST: ${{ secrets.TestURL }}
          #HOOK: ${{ secrets.HookURL }}

      - name: Setup Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Commit changes
        run: |
          git add .
          git commit -m "Update stats" || echo "No changes to commit"
          git push origin ${{ env.BRANCH_NAME }}
